version: '2'

services:
  
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
      - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"

  ros-master:
    image: fagnerpimentel/aprendendo_ros2:latest
    ipc: host
    volumes:
      - ./src:/home/robot/ws_aprendendo_ros2/src:rw
    depends_on:
      - xserver
    volumes_from:
      - xserver
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
    command:
      - /bin/bash
      - -c
      - |
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install && 
        source install/setup.bash &&
        xterm -hold -T Terminal -e "tmux" |
        ros2 run rqt_gui rqt_gui --perspective-file src/pacote_de_exemplos/config/Default.perspective 
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos exemplo.launch.py" 
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos display.launch.py" 
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos mapping_slam_toolbox.launch.py" 
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos mapping_cartographer.launch.py" 
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos navigation.launch.py" 
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos turtlebot.launch.py"
        # xterm -maximized -hold -T teste -e "ros2 launch pacote_de_exemplos navigation2.launch.py"
